#!/usr/bin/env python3
import subprocess, os, argparse, sys, random, mimetypes, logging, tty, termios
from getch import getch
from michimusemodels import *

logger = logging.getLogger("ffzanz")

def main():
  parser = argparse.ArgumentParser(description='Plays music from mr.scan.64 database with FFmpeg')
  args = parser.parse_args()
  try:
    while True:
      tracks = []
      for track in Track.select():
        tracks.append(track)
      random.shuffle(tracks)
      for track in tracks:
        print(track)
        playa = subprocess.Popen(['ffplay', '-nodisp', '-loglevel', 'quiet', '-autoexit', track.path])
        while playa.poll() is None:
          cmnd = getch()
          if 'n' in cmnd:
            playa.kill()
            break
          if 'q' in cmnd:
            playa.kill()
            sys.exit(0)
  except KeyboardInterrupt:
    sys.exit(0)

if __name__ == '__main__':
  main()
