#!/usr/bin/env python3
import subprocess, os, argparse, sys, random, mimetypes, logging, tty, termios
from michimusemodels import *

logger = logging.getLogger("ffzanz")

def getch():
  fd = sys.stdin.fileno()
  oldsets = termios.tcgetattr(fd)
  try:
    tty.setraw(sys.stdin.fileno())
    ch = sys.stdin.read(1)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, oldsets)
  return ch

def main():
  parser = argparse.ArgumentParser(description='Plays music from mr.scan.64 database with FFmpeg')
  args = parser.parse_args()
  try:
    while True:
      tracks = []
      for track in Track.select():
        tracks.append(track)
      random.shuffle(tracks)
      for track in tracks:
        print(track)
        playa = subprocess.Popen(['ffplay', '-nodisp', '-loglevel', 'quiet', track.path])
        while True:
          try:
            playa.wait(timeout=1)
            break
          except subprocess.TimeoutExpired:
            cmnd = getch()
            if 'n' in cmnd:
              playa.kill()
              break
            if 'q' in cmnd:
              playa.kill()
              sys.exit(0)
  except KeyboardInterrupt:
    sys.exit(0)

if __name__ == '__main__':
  main()
