#!/usr/bin/env python3
import datetime, subprocess, random, time, sys

def partofday():
    h = datetime.datetime.now().hour
    if h > 17:
        return "evening"
    elif h > 12:
        return "afternoon"
    elif h > 6:
        return "morning"
    else:
        return "night"

def sayings():
    return [
        "charging low orbit ion cannon",
        "submitting the last pull request",
        "fixing the last bug",
        "queueing cool tracks to check out tomorrow",
        "saving the world (to the least free file format)",
        "enjoying the %s" % partofday(),
        "playing banjo like a boss",
        "installing Arch Linux on every PC I can find",
        "becoming the greatest indie game developer in the world"
    ]

def printandsay(text, end='\n'):
    print(text, flush=True, end=end)
    subprocess.call(["espeak",text])

def main():
    printandsay("Icarus Analysis System")
    print("======================")
    printandsay("You invoked the halp request.")
    printandsay("The system will halp in 25 seconds.")
    printandsay("Now %s" % random.choice(sayings()), end='')
    print(" [", end='', flush=True)
    i = 0
    while i < 100:
        i = i + 1
        print(".", end='', flush=True)
        time.sleep(0.25)
    print("]", flush=True)
    print("The system will now halp:", flush=True)
    subprocess.call(['poweroff'])

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        printandsay("Halp request cancelled")
        sys.exit(0)
