#!/usr/bin/env python3
import datetime, subprocess, random, time, sys

def partofday():
    h = datetime.datetime.now().hour
    if h > 17:
        return "evening"
    elif h > 12:
        return "afternoon"
    elif h > 6:
        return "morning"
    else:
        return "night"

def sayings():
    return [
        "charging low orbit ion cannon",
        "submitting the last pull request",
        "fixing the last bug",
        "queueing cool tracks to check out tomorrow",
        "saving the world (to the least free file format)",
        "enjoying the %s" % partofday(),
        "playing banjo like a boss",
        "installing Arch Linux on every PC I can find",
        "becoming the greatest indie game developer in the world",
        "singing teenpop out loud",
        "helping primitive species evolve",
        "throwing pokeballs at people",
        "pwning noobs",
        "starting a flame war on Reddit",
        "correct horse battery staple"
    ]

def printandsay(text, end='\n', wait=True):
    print(text, end=end)
    sys.stdout.flush()
    if wait:
        subprocess.call(["espeak","-v", "english", text])
    else:
        subprocess.Popen(["espeak", "-v", "english", text])

def main():
    printandsay("Welcome to Icarus Analysis System")
    print("")
    printandsay("You invoked the halp request from %s terminal." % subprocess.check_output("tty",universal_newlines=True).rstrip())
    printandsay("The system will halp in 25 seconds.")
    printandsay("Now %s [" % random.choice(sayings()), end='', wait=False)

    for i in range(0, 99):
        print(".", end='')
        time.sleep(0.25)
        sys.stdout.flush()

    print("]")
    printandsay("The system will now halp:")
    subprocess.call(['poweroff'])

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        printandsay("Halp request cancelled", wait=False)
        sys.exit(0)
