#!/usr/bin/env python3

import datetime, random, time, sys, subprocess

def printandsay(text, end='\n', wait=True):
    print(text, end)
    if wait:
        subprocess.call(['espeak', text])
    else:
        subprocess.Popen(['espeak', text])

if __name__ == '__main__':
    printandsay("Initializing Icarus Analysis System", end='', wait=False)
    for i in range(0,99):
        print(".", end='')
        sys.stdout.flush()
        time.sleep(0.1)
    printandsay("Scanning the area for possible tracking")
    matrix = subprocess.Popen(["cmatrix"])
    time.sleep(10)
    matrix.terminate()
    
