#!/usr/bin/env python3
import subprocess
def main():
    text = subprocess.check_output("birthday", universal_newlines=True).strip()
    data = text.split('\n')
    for event in data:
        print(event)
        subprocess.call(["espeak",event])
if __name__ == '__main__':
    main()
