#!/usr/bin/env python3
import subprocess, argparse
def main():
    parser = argparse.ArgumentParser(description='Reads birthdays out loud')
    parser.add_argument('--days', type=int, default=90, help="Defines how many days in future birthday program has to lookup")
    args = parser.parse_args()
    text = subprocess.check_output(["birthday", "-W", "%i" % args.days], universal_newlines=True).strip()
    data = text.split('\n')
    for event in data:
        print(event)
        subprocess.call(["espeak",event])
if __name__ == '__main__':
    main()
