#!/usr/bin/env python3
import curses, datetime, dbus
import michispotify as spotify
import michimpris as mpris
class SpotifyShell(object):
    def redraw(self):
        self.title = self.spt.title()
        self.album = self.spt.album()
        self.artist = self.spt.artist()
        self.time = datetime.datetime.now().time()
        self.dims = self.screen.getmaxyx()
        self.screen.clear()
        self.screen.border()
        titlebar = " SptSH "
        self.screen.addstr(0, round(self.dims[1]/2-len(titlebar)/2), titlebar, curses.color_pair(5))
        self.screen.addstr(2, 2, "Now playing", curses.color_pair(1))
        if len(self.title) > (self.dims[1]-6):
            self.screen.addstr(3, 4, self.title[:(self.dims[1]-9)].rstrip().decode() + "...", curses.color_pair(2))
        else:
            self.screen.addstr(3, 4, self.title, curses.color_pair(2))
        self.screen.addstr(4, 2, "by", curses.color_pair(1))
        if len(self.artist) > (self.dims[1]-6):
            self.screen.addstr(5, 4, self.artist[:(self.dims[1]-9)].rstrip().decode() + "...", curses.color_pair(3))
        else:
            self.screen.addstr(5, 4, self.artist, curses.color_pair(3))
        self.screen.addstr(6, 2, "from", curses.color_pair(1))
        if len(self.album) > (self.dims[1]-6):
            self.screen.addstr(7, 4, self.album[:(self.dims[1]-9)].rstrip().decode() + "...", curses.color_pair(4))
        else:
            self.screen.addstr(7, 4, self.album, curses.color_pair(4))
        if self.time24:
            self.screen.addstr(9, 2, self.time.strftime("%H:%M"), curses.color_pair(5))
        else:
            self.screen.addstr(9, 2, self.time.strftime("%I:%M %p"), curses.color_pair(5))
        self.screen.refresh()
    def main(self, screen):
        self.screen = screen
        curses.curs_set(0)
        self.time24 = True
        curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLACK)
        curses.init_pair(2, curses.COLOR_RED, curses.COLOR_BLACK)
        curses.init_pair(3, curses.COLOR_GREEN, curses.COLOR_BLACK)
        curses.init_pair(4, curses.COLOR_YELLOW, curses.COLOR_BLACK)
        curses.init_pair(5, curses.COLOR_BLACK, curses.COLOR_WHITE)
        try:
            self.spt = spotify.SpotifyController()
        except dbus.exceptions.DBusException:
            try:
                self.spt = mpris.MPRISController('org.mpris.MediaPlayer2.tomahawk')
            except dbus.exceptions.DBusException:
                self.spt = mpris.DummyController()
        self.screen.nodelay(1)
        self.redraw()
        while True:
            event = self.screen.getch()
            if event == ord("q"):
                break
            elif event == ord("n") or event == curses.KEY_RIGHT:
                self.spt.forward()
            elif event == ord("b") or event == curses.KEY_LEFT:
                self.spt.previous()
            elif event == ord(";"):
                self.time24 = not self.time24
                self.redraw()
            elif event == ord(" "):
                self.spt.playpause()
            if self.title != self.spt.title() or self.album != self.spt.album() or self.artist != self.spt.artist() or self.time.minute != datetime.datetime.now().time().minute or self.time.hour != datetime.datetime.now().time().hour or self.dims != self.screen.getmaxyx():
                self.redraw()

def main(screen):
    SpotifyShell().main(screen)

if __name__ == '__main__':
    curses.wrapper(main)
