#!/usr/bin/env python3
from subprocess import Popen, check_output, call
def gettty():
    return check_output("tty", universal_newlines=True).strip()
def getwhoami():
    return check_output("whoami", universal_newlines=True).strip()
def printandsay(text, end='\n', wait=False):
    print(text, end)
    if wait:
        call(['espeak', text])
    else:
        Popen(['espeak',text])
def main():
    printandsay("""Welcome to the Icarus Workstation.
You have now logged in as %s from %s.
Please remember that you are accessing a Workstation that contains sensitive data. Disclosing them will lead to the situation where all your base are belong to us.""" % (getwhoami(), gettty()))

if __name__ == '__main__':
    main()
